spring.application.name=springSecurityDemo

#spring.datasource.url=dev-ono-click-db.cupipq7lwo0c.ap-south-1.rds.amazonaws.com
#spring.datasource.username=onclick
#spring.datasource.password=A5mngXllyny1oEiXgh8bhgMA
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dev-ono-click-db.cupipq7lwo0c.ap-south-1.rds.amazonaws.com:5432/devonoclickdb
spring.datasource.dbhost=dev-ono-click-db.cupipq7lwo0c.ap-south-1.rds.amazonaws.com
spring.datasource.dbname=devonoclickdb
spring.datasource.password=A5mngXllyny1oEiXgh8bhgMA
spring.datasource.username=onoclick

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true